apiVersion: v1
kind: Pod
metadata:
  name: initpod
spec:
  containers:
  - name: after-init
    image: busybox
    command: ['sh', '-c', 'echo its running! && sleep 3600']
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'until ls /tmp/init 2>/dev/null; do echo waiting for my file; sleep 2; done;']
