apiVersion: v1
kind: Pod
metadata:
  name: too-big
  namespace: limits-example
spec:
  containers:
  - image: busybox
    args: ["sleep", "9999999"]
    name: main
    resources:
      requests:
        cpu: 1.5
