apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
  labels:
    role: web
spec:
  containers:
  - name: nginx-cm
    image: nginx
    volumeMounts:
    - name: 
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: 
    configMap:
      name: 
      items:
      - key: 
        path: 
