---
- name: variable playbook test
  hosts: localhost

  tasks:
  - name: Ensure httpd package is present
    yum:
      name: httpd
      state: latest
    register: httpd_results

  - name:
    service:
      name: httpd
      state: restarted
    when: httpd_results.changed
