- hosts: workers
  remote_user: root
  vars: 
    ansible_ssh_private_key_file: "/home/ansible/.ssh/id_rsa"
  vars_files:
    - /var/users.yml
  tasks:
    - name: adding several users
      user:
        name: "{{ item.name }}"
        state: present
        comment: "{{ item.comment }}"
        password: "$1$*)^%$CeUUJM&v#0pQhHjqjpqX1"
        update_password: on_create
        createhome: yes
        groups: "{{ item.groups }}"
      with_items: "{{ users }}"