---
- name: Lab1
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Download index to the reading directory
      get_url:
        url: https://raw.githubusercontent.com/Josep-Andreu/Optativa-cloud/master/index.html
        dest: /usr/share/nginx/html/index.html
        mode: '0440'
      notify:
      - Restart nginx


  handlers:
    - name: Restart nginx
      become: true
      service:
        name: nginx
        state: restarted
