---
- name: Lab2
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Create users from file
      read_csv:
        path: username.csv
      register: user_list
      delegate_to: localhost

    - name: Display user_list data
      debug:
        msg: "{{ user_list.list }}"

    - name: Print dictionaries
      debug:
        msg: "{{ item.Username }}"
      loop: "{{ user_list.list }}"

    - name: Create users from the file
      user:
        name: "{{ item.Username }}"
        state: present
      loop: "{{ user_list.list }}"
