kind: Deployment
apiVersion: apps/v1
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat-deploy

spec:
  ports:
    - protocol: TCP
      name: admin
      port: 8080
      nodePort: 30001
  replicas: 4
  selector:
    matchLabels:
      app: tomcat
    template:
      metadata:
        labels:
          app: tomcat
      spec:
        containers:
          - name: tomcat
            image: tomcat:8-jre8-openjdk
            resources:
              limits:
                cpu: 0.25
                memory: 256Mi
              ports:
                - containerPort: 8085
