apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ping
  name: ping
spec:
  containers:
  - args:
    - ping
    - -c
    - "4"
    - 192.168.4.6
    image: busybox
    name: ping
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
